# Práctica 1.1 — Probabilidad y Estadística
## Análisis de la evolución poblacional mundial

**Objetivo:** utilizar datos reales de población para comprobar el entorno de análisis y aplicar medidas estadísticas descriptivas básicas con Python, Pandas y NumPy.

En esta práctica se utilizarán únicamente los datos históricos de cambio anual de población.

# **Actividad 1** - Identificación de la fuente

**Propósito:** Reconocer la procedencia del conjunto de datos antes de utilizarlo y dcumentar correctamente su fuente.

## **Cita de la fuente:** 
- **United Nations, World Population Prospects (2024)**
- >UN, World Population Prospects (2024) – processed by Our World in Data. “Annual change in population – UN WPP” [dataset]. United Nations, “World Population Prospects”; United Nations, “World Population Prospects - Interim Update” [original data].

- **Preguntas:**
    - *¿Quién produjo originalmente los datos?* Son datos recopilados de un censo realizado en la unión europea en el 2024.
    - *¿Qué organización los procesa para su utilización en Our World in Data?* Según sus archivos, los datos provienen de diferentes proveedores u organizaciones, por lo que no existe una única eorganización encargada de procesarlos para ser utilizados posteriormente.
    - *¿Qué representa la variable que analizarás?*

**Respuesta sobre la variable:** `Annual change in population` representa el cambio neto anual de población, calculado como la diferencia entre la población del 1 de julio de dos años consecutivos. Incluye nacimientos, defunciones y migración, y se mide en personas.

**Aclaración según la documentación de OWID:**

1. Los datos fueron producidos originalmente por **United Nations, World Population Prospects (2024)**.
2. **Our World in Data** procesa y documenta los datos para su utilización en su plataforma.
3. La variable histórica utilizada es el cambio neto anual de población, expresado en personas.

# Actividad 2 - Carga y exploración de datos. 

**Propósito:** Comprobar que el entorno de Python, Pandas y Jupyter funciona correctamente y realizar una primera exploración del dataset.

In [1]:
##2.1 Importar las bibliotecas

import pandas as pd
import numpy as np

##2.2 Cargar el archivo CSV
df = pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

In [6]:
##2.3 Explorar el DataFrame
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [7]:
df.shape

(38400, 5)

In [8]:
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [9]:
df.dtypes

Entity                                      str
Code                                        str
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [10]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [11]:
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [12]:
df["Entity"].nunique()

256

### Preguntas - Actividad 2: 
- *¿Cuántas filas y columnas tiene el dataset?* Tiene 38400 filas y 5 columnas.
- *¿Qué tipo de datos contiene la variable "year"?* De tipo "int" o entero.
- *¿Existen valores faltantes?* Sí, hay varios valores faltantes principalmente en las columnas *Code, Annual change in population* y *Annual population change (projected)*. 
- *¿Cuántas entidades diferentes contiene el dataset?* 256.

# Actividad 3 - Estadística descriptiva

**Propósito:** Aplicar medidas estadísticas básicas a una variable poblacional.

In [13]:
df_2006 = df[df['Year'] == 2006]
df_mex = df[(df["Entity"] == "Mexico") & (df["Year"] >= 2006) & (df["Annual change in population"])]
df_mex.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN
22258,Mexico,MEX,2009,1625434.0,NaN
22259,Mexico,MEX,2010,1624178.0,NaN

In [14]:
df_2006_2020_mex = df [(df["Year"] >= 2006) & (df["Year"] <= 2020) & (df["Code"] == "MEX")]
df_2006_2020_mex

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN
22258,Mexico,MEX,2009,1625434.0,NaN
22259,Mexico,MEX,2010,1624178.0,NaN
22260,Mexico,MEX,2011,1619605.0,NaN
22261,Mexico,MEX,2012,1574705.0,NaN
22262,Mexico,MEX,2013,1525364.0,NaN
22263,Mexico,MEX,2014,1440693.0,NaN
22264,Mexico,MEX,2015,1288045.0,NaN
22265,Mexico,MEX,2016,1179034.0,NaN
22266,Mexico,MEX,2017,1148708.0,NaN
22267,Mexico,MEX,2018,1173661.0,NaN
22268,Mexico,MEX,2019,1189265.0,NaN
22269,Mexico,MEX,2020,1036075.0,NaN

In [15]:
df_extraccion_rango_mex = df_2006_2020_mex[["Entity","Year","Annual change in population"]]
df_extraccion_rango_mex

       Entity  Year  Annual change in population
22255  Mexico  2006                    1442162.0
22256  Mexico  2007                    1520690.0
22257  Mexico  2008                    1599930.0
22258  Mexico  2009                    1625434.0
22259  Mexico  2010                    1624178.0
22260  Mexico  2011                    1619605.0
22261  Mexico  2012                    1574705.0
22262  Mexico  2013                    1525364.0
22263  Mexico  2014                    1440693.0
22264  Mexico  2015                    1288045.0
22265  Mexico  2016                    1179034.0
22266  Mexico  2017                    1148708.0
22267  Mexico  2018                    1173661.0
22268  Mexico  2019                    1189265.0
22269  Mexico  2020                    1036075.0

In [16]:
df_extraccion_rango_mex.mean(numeric_only=True)

Year                           2.013000e+03
Annual change in population    1.399170e+06
dtype: float64

In [17]:
column = 'Annual change in population'
media = df_2006[column].mean()
mediana = df_2006[column].median()
varianza = df_2006[column].var()
desviacion = df_2006[column].std()
minimo = df_2006[column].min()
maximo = df_2006[column].max()

print(f"Resultados para el año 2006:")
print(f"Media: {media}")
print(f"Mediana: {mediana}")
print(f"Varianza: {varianza}")
print(f"Desviación estándar: {desviacion}")
print(f"Valor mínimo: {minimo}")
print(f"Valor máximo: {maximo}")

Resultados para el año 2006:
Media: 2320433.41015625
Mediana: 46815.5
Varianza: 108720938849925.55
Desviación estándar: 10426933.338711126
Valor mínimo: -494938.0
Valor máximo: 84481887.0

In [18]:
entidad_min = df_2006[df_2006[column] == minimo]['Entity'].values[0]
entidad_max = df_2006[df_2006[column] == maximo]['Entity'].values[0]

print(f"El valor de la Media es: {media}")
print(f"El valor de la Mediana es: {mediana}")
print(f"La entidad con el valor mínimo es: {entidad_min}")
print(f"La entidad con el valor máximo es: {entidad_max}")

El valor de la Media es: 2320433.41015625
El valor de la Mediana es: 46815.5
La entidad con el valor mínimo es: Russia
La entidad con el valor máximo es: World

In [3]:
# Resumen estadístico del año histórico seleccionado
year_selected = 2006
column = "Annual change in population"
df_2006 = df.loc[df["Year"].eq(year_selected)]
resumen_2006 = pd.Series({
    "Media": df_2006[column].mean(),
    "Mediana": df_2006[column].median(),
    "Varianza": df_2006[column].var(),
    "Desviación estándar": df_2006[column].std(),
    "Mínimo": df_2006[column].min(),
    "Máximo": df_2006[column].max(),
})
resumen_2006

Media                  2.320433e+06
Mediana                4.681550e+04
Varianza               1.087209e+14
Desviación estándar    1.042693e+07
Mínimo                -4.949380e+05
Máximo                 8.448189e+07
dtype: float64

# Actividad 4 - Comprobación del Entorno

**Propósito:** Comprobar que el notebook está utilizando correctamente las herramientas configuradas para la práctica.

In [19]:
import sys

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2

In [20]:
df.loc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [21]:
df.iloc[10000]

Entity                                  Equatorial Guinea
Code                                                  GNQ
Year                                                 2051
Annual change in population                           NaN
Annual population change (Projected)              46407.0
Name: 10000, dtype: object

In [24]:
df.loc[:,["Entity","Year","Annual change in population"]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [26]:
df.loc[10000,["Entity","Year","Annual change in population"]]

Entity                         Equatorial Guinea
Year                                        2051
Annual change in population                  NaN
Name: 10000, dtype: object

In [29]:
df.loc[(df["Entity"] == "Mexico") & (df["Year"] == 2020) & (df["Annual change in population"])]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [31]:
df.iloc[0:5]

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [33]:
df.iloc[:,[0,2,3]]

            Entity  Year  Annual change in population
0      Afghanistan  1951                     103163.0
1      Afghanistan  1952                     108441.0
2      Afghanistan  1953                     108919.0
3      Afghanistan  1954                     111251.0
4      Afghanistan  1955                     119027.0
...            ...   ...                          ...
38395     Zimbabwe  2096                          NaN
38396     Zimbabwe  2097                          NaN
38397     Zimbabwe  2098                          NaN
38398     Zimbabwe  2099                          NaN
38399     Zimbabwe  2100                          NaN

[38400 rows x 3 columns]

In [39]:
de_Mario = df.loc[(df["Entity"] == "Venezuela") & (df["Year"] > 2005) & (df["Year"] < 2023)]

mediaM = de_Mario[column].mean()

print(f"Media: {mediaM}")

Media: 83954.0

## Reproducibilidad final

Al ejecutar nuevamente las celdas desde el inicio, el notebook carga el CSV, explora sus columnas y calcula las medidas descriptivas usando el mismo procedimiento. La celda siguiente confirma las versiones activas del entorno.

In [4]:
import sys

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.14.7 (tags/v3.14.7:823f032, Aug  5 2026, 10:51:32) [MSC v.1944 64 bit (AMD64)]
Pandas: 3.0.5
NumPy: 2.5.2